[package]
name = "terminal-palette"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
crossterm = "0.29.0"
derive_setters = "0.1.8"
palette = "0.7.6"
rand = "0.9.2"
ratatui = "0.29.0"
strum = "0.27.2"
strum_macros = "0.27.2"
